name: CI

on: [push, pull_request]

jobs:
  linux-gcc:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        gcc-version: [8, 9]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: newest gcc repo
        run: |
          sudo apt install -y software-properties-common && \
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test && \
          sudo apt update
      - name: install gcc and gcc-plugin
        run: sudo apt install -y gcc-${{ matrix.gcc-version }} gcc-${{ matrix.gcc-version }}-plugin-dev
      - name: build
        run: gcc-${{ matrix.gcc-version }} --version
      - name: check-plugin
        run: gcc-${{ matrix.gcc-version }} -print-file-name=plugin
